### ISSUE TITLE
Preset buttons not working in editor

### ISSUE THREAD

**Issue by Xento** [berrywhite96/lovelace-shutter-row#26]
I can't add preset buttons via the editor:
Uncaught TypeError: Cannot add property preset_buttons, object is not extensible
    at ShutterRowEditor._addPresetItem (shutter-row.js:495:41)
    at H.handleEvent (shutter-row.js:19:7199)

When I define them in code it shows up the editor isn't working:
shutter-row.js:664  Uncaught TypeError: Cannot add property undefined, object is not extensible
    at ShutterRowEditor._presetChanged (shutter-row.js:664:67)
    at H.handleEvent (shutter-row.js:19:7199)
    at o (fire_event.ts:76:8)
    at ShadowRoot.<anonymous> (ha-form.ts:180:7)
    at o (fire_event.ts:76:8)
    at F.value (hui-action-editor.ts:190:7)
    at D.handleEvent (lit-html.ts:2010:29)
    at Object.notifySelected (mwc-list-base.ts:409:14)
    at f.setSingleSelectionAtIndex_ (mwc-list-foundation.ts:410:18)
    at f.setSelectedIndex (mwc-list-foundation.ts:194:12)

**Comment by berrywhite96** [comment]
Can you post the version you're using?

**Comment by berrywhite96** [comment]
Closed due inactivity.
